import { StrictMode } from 'react'
import { renderToString } from 'react-dom/server'
import {
  createStaticHandler,
  createStaticRouter,
  StaticRouterProvider,
} from 'react-router-dom'
import { routes } from './routes'
import { getPageMeta } from './features/seo/pageMeta'

// No CSS import here: Tailwind's stylesheet is generated by the client build and
// linked in index.html. The server render only needs to emit class names.

// Re-exported so the prerender script can enumerate paths from the same built
// bundle it renders with.
export { getRoutePaths } from './features/seo/routePaths'

// Built once by the Vite SSR build and driven by scripts/prerender.mjs. The
// static handler reuses the exact same route tree the browser router uses
// (routes.tsx), so prerendered markup matches what the client hydrates.
const handler = createStaticHandler(routes)

export interface RenderResult {
  /** The app markup to inject into <div id="root">, incl. RR hydration script. */
  html: string
  /** The <head> tags (title, description, canonical, Open Graph). */
  head: string
}

/**
 * Renders one route to static HTML. `siteUrl` (no trailing slash) supplies the
 * absolute origin for canonical/OG URLs; it's passed in from the prerender
 * script rather than read from the environment here.
 */
export async function render(
  path: string,
  siteUrl: string,
): Promise<RenderResult> {
  const context = await handler.query(new Request(`http://localhost${path}`))
  if (context instanceof Response) {
    // We define no loaders/actions, so a Response (redirect) shouldn't occur.
    throw new Error(`Unexpected Response while prerendering ${path}`)
  }

  const router = createStaticRouter(handler.dataRoutes, context)
  const html = renderToString(
    <StrictMode>
      <StaticRouterProvider router={router} context={context} />
    </StrictMode>,
  )

  return { html, head: buildHead(path, siteUrl) }
}

const escapeAttr = (s: string) =>
  s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')

function buildHead(path: string, siteUrl: string): string {
  const { title, description } = getPageMeta(path)
  const canonical = `${siteUrl}${path}`
  const ogImage = `${siteUrl}/og-default.png`
  const t = escapeAttr(title)
  const d = escapeAttr(description)

  return [
    `<title>${t}</title>`,
    `<meta name="description" content="${d}" />`,
    `<link rel="canonical" href="${escapeAttr(canonical)}" />`,
    `<meta property="og:type" content="website" />`,
    `<meta property="og:site_name" content="Yaku Palace" />`,
    `<meta property="og:title" content="${t}" />`,
    `<meta property="og:description" content="${d}" />`,
    `<meta property="og:url" content="${escapeAttr(canonical)}" />`,
    `<meta property="og:image" content="${escapeAttr(ogImage)}" />`,
    `<meta name="twitter:card" content="summary_large_image" />`,
    `<meta name="twitter:title" content="${t}" />`,
    `<meta name="twitter:description" content="${d}" />`,
    `<meta name="twitter:image" content="${escapeAttr(ogImage)}" />`,
  ].join('\n    ')
}
